### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by sje397** [sje397/TodoApp#1]
My app is complete. Please review. /cc @codepathreview @codepath

**Comment by sje397** [comment]
I added a toast message in case there is an error saving the list. More to come :)

**Comment by nidhi1608** [comment]
Scott,

Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction.

We are reviewing the submissions right now and will get in touch with you via email a few days after the submission closing date, October 2nd, 2015. In the mean time, you may consider working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and let us know if you have any questions.

**Comment by sje397** [comment]
I have pushed changes:
- make storage more abstract, use SQL for storage (via ActiveAndroid)
- add priority and due date
- use DatePickerDialog and TimePickerDialog to edit due date
- use Spinner to edit priority
- sort by priority
- custom list adapter with round shape and background colors

**Comment by nidhi1608** [comment]
Excellent progress Scott. Nice to see you were able to work on all of the optionals. Since you still have a lot of time before the class starts, I would encourage you to play around with the app a bit more. You may benchmark a couple of popular todo apps on the play store and go from there. Mobile is all about adding minor details and UI polish to your app. Thats what takes an app to the next level.
